version: 2.1
jobs:

  build-docs:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Install dependencies for headless rendering
          command: |
            sudo apt update
            sudo apt install -y qt6-base-dev xvfb libegl1 libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 libxcb-cursor0 x11-utils

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade wheel setuptools pip
            pip install -r requirements.txt
            pip install .
            pip list

      - restore_cache:
          # NOTE: The v#.# refers to the cellsam published model version.
          # The _### postfix is intended for manual cache invalidation as necessary
          keys:
            - model-cache-v1.2_000

      - run:
          name: Build site
          # Gallery + Tutorial w/out GPU can take a while
          no_output_timeout: 30m
          command: |
            source venv/bin/activate
            # n = nitpicky (broken links), W = warnings as errors,
            # T = full tracebacks, keep-going = run to completion even with errors
            xvfb-run --auto-servernum make -C docs/ SPHINXOPTS="-WT --keep-going" html

      - save_cache:
          key: model-cache-v1.2_000
          paths:
            - ~/.deepcell

      - store_artifacts:
          path: docs/_build/html

      - persist_to_workspace:
          root: docs/_build
          paths: html

workflows:
  version: 2.1
  build:
    jobs:
      - build-docs
