version: 2.1
jobs:

  build-docs:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Install Qt dependencies
          command: |
            sudo apt update && sudo apt upgrade
            sudo apt install -y qt6-base-dev

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade wheel setuptools pip
            pip install -r requirements.txt
            pip install .
            pip list

      - run:
          name: Build site
          # Gallery + Tutorial w/out GPU can take a while
          no_output_timeout: 30m
          command: |
            source venv/bin/activate
            # n = nitpicky (broken links), W = warnings as errors,
            # T = full tracebacks, keep-going = run to completion even with errors
            QT_QPA_PLATFORM=offscreen make -C docs/ SPHINXOPTS="-WT --keep-going" html

      - store_artifacts:
          path: site/_build/html

      - persist_to_workspace:
          root: site/_build
          paths: html

  deploy-docs:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - attach_workspace:
          at: site/_build

      - run:
          name: Install deploy dependencies
          command: python3 -m pip install --user ghp-import

      - run:
          name: Configure git
          command: |
            git config --global user.name "ci-doc-deploy-bot"
            git config --global user.email "ci-doc-deploy-bot@nomail"
            git config --global push.default simple

      - add_ssh_keys:
          fingerprints:
            - TODO

      - run:
          name: Deploy via gh-pages
          command: |
            ghp-import -n -f -p -m "[skip ci] docs built of $CIRCLE_SHA1" site/_build/html

workflows:
  version: 2.1
  build:
    jobs:
      - build-docs
      - deploy-docs:
          requires:
            - build-docs
          filters:
            branches:
              only: main
